config:
  gcp:project: apex-check-deposit-prod  # replace with your GCP project ID
  gcp:region: us-central1
  apex-check-deposit:sqlTier: db-g1-small
  apex-check-deposit:minInstances: "1"
  apex-check-deposit:sqlBackups: "true"
  apex-check-deposit:enableSecrets: "true"
  apex-check-deposit:apiTag: latest
  apex-check-deposit:vssTag: latest
  apex-check-deposit:settlementTag: latest
